export const adminUser = {
  id: "user-1",
  username: "tester",
  role: "admin",
  displayName: "Test User",
  status: "active",
  lastLoginAt: "2026-05-30",
};

export const normalUser = {
  ...adminUser,
  id: "user-2",
  username: "viewer",
  role: "user",
  displayName: "View User",
};

export const shipmentRows = [
  {
    date: new Date("2024-01-15T00:00:00.000Z"),
    monthLabel: "Jan 2024",
    year: 2024,
    quarter: "Q1",
    yearQuarter: "2024 Q1",
    monthNumber: 1,
    monthName: "January",
    yearMonth: "2024-01",
    bookingNo: "BK-001",
    jobNo: "JOB-001",
    shipper: "Alpha Logistics",
    liner: "Liner A",
    pol: "BKK",
    pod: "TYO",
    country: "Japan",
    port: "Tokyo",
    destination: "Tokyo",
    qty: 2,
    unit: "40HC",
    teu: 4,
    status: "Loaded",
    saleName: "Pan",
    trade: "Asia",
    carrier: "Carrier A",
    route: "BKK -> Tokyo",
  },
  {
    date: new Date("2024-04-10T00:00:00.000Z"),
    monthLabel: "Apr 2024",
    year: 2024,
    quarter: "Q2",
    yearQuarter: "2024 Q2",
    monthNumber: 4,
    monthName: "April",
    yearMonth: "2024-04",
    bookingNo: "BK-002",
    jobNo: "JOB-002",
    shipper: "Beta Trading",
    liner: "Liner B",
    pol: "BKK",
    pod: "HAM",
    country: "Germany",
    port: "Hamburg",
    destination: "Hamburg",
    qty: 1,
    unit: "20DC",
    teu: 1,
    status: "Pending",
    saleName: "Mint",
    trade: "Europe",
    carrier: "Carrier B",
    route: "BKK -> Hamburg",
  },
  {
    date: new Date("2025-02-05T00:00:00.000Z"),
    monthLabel: "Feb 2025",
    year: 2025,
    quarter: "Q1",
    yearQuarter: "2025 Q1",
    monthNumber: 2,
    monthName: "February",
    yearMonth: "2025-02",
    bookingNo: "BK-003",
    jobNo: "JOB-003",
    shipper: "Gamma Export",
    liner: "Liner C",
    pol: "BKK",
    pod: "SIN",
    country: "Singapore",
    port: "Singapore",
    destination: "Singapore",
    qty: 3,
    unit: "40HC",
    teu: 6,
    status: "Loaded",
    saleName: "Pan",
    trade: "Asia",
    carrier: "Carrier A",
    route: "BKK -> Singapore",
  },
];

export const workbookData = {
  metadata: {
    source: "unit-fixture.xlsx",
    shipments: shipmentRows.length,
  },
  detailData: shipmentRows,
};

export const apiWorkbookData = {
  ...workbookData,
  detailData: shipmentRows.map((row) => ({
    ...row,
    date: row.date.toISOString(),
  })),
};
